"""Seed for scrypt

Revision ID: 145d49198f77
Revises: 27c484d6138e
Create Date: 2014-07-06 04:27:14.053026

"""

# revision identifiers, used by Alembic.
revision = '145d49198f77'
down_revision = '27c484d6138e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_seed', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_seed')
    ### end Alembic commands ###
