"""Added email to check alembic autogenerate

Revision ID: 27c484d6138e
Revises: 2ea6e977b417
Create Date: 2014-07-05 19:54:53.754269

"""

# revision identifiers, used by Alembic.
revision = '27c484d6138e'
down_revision = '2ea6e977b417'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###
