"""lets just stick with bcrypt

Revision ID: 339e55194503
Revises: a3d94d9fd4b
Create Date: 2014-07-18 02:25:52.341983

"""

# revision identifiers, used by Alembic.
revision = '339e55194503'
down_revision = 'a3d94d9fd4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_seed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_seed', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    ### end Alembic commands ###
