"""passwords stuffs

Revision ID: 404ee8a4a2b8
Revises: 145d49198f77
Create Date: 2014-07-06 04:42:46.541833

"""

# revision identifiers, used by Alembic.
revision = '404ee8a4a2b8'
down_revision = '145d49198f77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###
