"""added google oauth data

Revision ID: 5a5b5b13534d
Revises: 339e55194503
Create Date: 2014-08-20 02:28:49.915192

"""

# revision identifiers, used by Alembic.
revision = '5a5b5b13534d'
down_revision = '339e55194503'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('google_token', sa.String(length=256), nullable=True))
    op.drop_column('user', 'token')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('user', 'google_token')
    op.drop_column('user', 'google_id')
    ### end Alembic commands ###
